services:
  db:
    image: postgres:16.4
    container_name: backend_api_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notification-system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5555:80"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
